# Generated by Django 3.1.6 on 2021-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('enroll_no', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('batch', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=3)),
            ],
        ),
    ]
