# Generated by Django 3.1.6 on 2021-03-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buySell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('enroll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
