# Generated by Django 3.1.6 on 2021-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210325_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysell',
            name='id',
        ),
        migrations.AlterField(
            model_name='buysell',
            name='enroll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
