# Generated by Django 3.1.6 on 2021-04-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210401_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buysell',
            name='enroll_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_no',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
